<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectLangCompApprenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('project_lang_comp_apprens')->insert([
            // Académique
            // -------------------------------------------------------------------------------------- Acta&Verba
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 1,
                'competence_id' => 1,
                'language_id' => 9,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 3,
                'competence_id' => 2,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 6,
                'competence_id' => 3,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 12,
                'competence_id' => 4,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 13,
                'competence_id' => 5,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 14,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 15,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 21,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 22,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 23,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 24,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 25,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 26,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 38,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 50,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 51,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 52,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 53,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 55,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 1,
                'apprentissage_critique_id' => 56,
                'competence_id' => null,
                'language_id' => null,
            ],
            // -------------------------------------------------------------------------------------- PortfolioS2
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 1,
                'competence_id' => 1,
                'language_id' => 1,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 2,
                'competence_id' => 2,
                'language_id' => 2,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 3,
                'competence_id' => 3,
                'language_id' => 3,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 4,
                'competence_id' => 4,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 5,
                'competence_id' => 5,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 6,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 12,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 13,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 14,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 15,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 21,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 22,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 23,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 24,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 25,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 26,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 33,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 34,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 35,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 36,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 37,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 38,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 50,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 51,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 52,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 53,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 54,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 55,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 2,
                'apprentissage_critique_id' => 56,
                'competence_id' => null,
                'language_id' => null,
            ],
            // -------------------------------------------------------------------------------------- LAN
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 7,
                'competence_id' => 1,
                'language_id' => 1,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 8,
                'competence_id' => 2,
                'language_id' => 2,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 18,
                'competence_id' => 3,
                'language_id' => 3,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 19,
                'competence_id' => 4,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 20,
                'competence_id' => 5,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 27,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 28,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 29,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 30,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 31,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 39,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 40,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 42,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 43,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 44,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 59,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 60,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 61,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 3,
                'apprentissage_critique_id' => 62,
                'competence_id' => null,
                'language_id' => null,
            ],
            // -------------------------------------------------------------------------------------- TELOCULTURE
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 10,
                'competence_id' => 1,
                'language_id' => 1,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 11,
                'competence_id' => 2,
                'language_id' => 2,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 16,
                'competence_id' => 4,
                'language_id' => 3,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 17,
                'competence_id' => 5,
                'language_id' => 5,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 39,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 40,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 42,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 43,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 44,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 57,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 58,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 60,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 61,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 4,
                'apprentissage_critique_id' => 62,
                'competence_id' => null,
                'language_id' => null,
            ],
            // Professionnel
            // -------------------------------------------------------------------------------------- Acta&Verba
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => 2,
                'language_id' => 9,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => 3,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => 4,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => 5,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 5,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            // -------------------------------------------------------------------------------------- PortfolioS2
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => 1,
                'language_id' => 1,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => 2,
                'language_id' => 2,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => 3,
                'language_id' => 3,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => 4,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => 5,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 6,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            // -------------------------------------------------------------------------------------- LAN
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => 1,
                'language_id' => 1,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => 2,
                'language_id' => 2,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => 3,
                'language_id' => 3,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => 4,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => 5,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 7,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            // -------------------------------------------------------------------------------------- TELOCULTURE
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => 1,
                'language_id' => 1,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => 2,
                'language_id' => 2,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => 4,
                'language_id' => 3,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => 5,
                'language_id' => 5,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
            [
                'project_id' => 8,
                'apprentissage_critique_id' => null,
                'competence_id' => null,
                'language_id' => null,
            ],
        ]);
    }
}
